-- Add Sample Products to DreamFit Database
-- Run this in Supabase SQL Editor to add test products

INSERT INTO products (
    name,
    description,
    price,
    discount_price,
    images,
    category,
    sizes,
    colors,
    in_stock,
    stock_quantity,
    featured,
    tags,
    rating,
    num_reviews
) VALUES
(
    'Elegant Evening Dress',
    'Perfect for special occasions and evening events. This stunning dress features elegant design with premium fabric that drapes beautifully.',
    2999.00,
    2499.00,
    ARRAY['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500'],
    'Dresses',
    ARRAY['XS', 'S', 'M', 'L', 'XL'],
    ARRAY['Black', 'Navy', 'Burgundy', 'Emerald'],
    true,
    25,
    true,
    ARRAY['evening', 'formal', 'party'],
    4.5,
    45
),
(
    'Casual Summer Dress',
    'Light and comfortable dress perfect for everyday wear. Made with breathable fabric ideal for warm weather.',
    1499.00,
    1299.00,
    ARRAY['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500', 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=500'],
    'Dresses',
    ARRAY['S', 'M', 'L', 'XL'],
    ARRAY['White', 'Blue', 'Pink', 'Yellow'],
    true,
    40,
    true,
    ARRAY['casual', 'summer', 'comfortable'],
    4.7,
    89
),
(
    'Professional Blazer',
    'Sophisticated blazer for the modern professional. Tailored fit with premium fabric for a polished look.',
    3499.00,
    2999.00,
    ARRAY['https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=500'],
    'Tops',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    ARRAY['Black', 'Grey', 'Navy', 'Beige'],
    true,
    30,
    true,
    ARRAY['formal', 'office', 'professional'],
    4.6,
    67
),
(
    'Floral Maxi Dress',
    'Beautiful floral print maxi dress perfect for outdoor events and summer gatherings. Flowing silhouette with comfortable fit.',
    2299.00,
    1899.00,
    ARRAY['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500', 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500'],
    'Dresses',
    ARRAY['S', 'M', 'L'],
    ARRAY['Floral Blue', 'Floral Pink', 'Floral White'],
    true,
    20,
    true,
    ARRAY['maxi', 'floral', 'summer', 'casual'],
    4.8,
    112
),
(
    'Classic White Shirt',
    'Timeless white shirt that never goes out of style. Versatile piece perfect for both casual and formal occasions.',
    1299.00,
    999.00,
    ARRAY['https://images.unsplash.com/photo-1624206112918-f140f087f9b5?w=500'],
    'Tops',
    ARRAY['XS', 'S', 'M', 'L', 'XL'],
    ARRAY['White', 'Ivory'],
    true,
    50,
    false,
    ARRAY['basic', 'classic', 'versatile'],
    4.4,
    156
),
(
    'Party Cocktail Dress',
    'Show-stopping cocktail dress perfect for parties and celebrations. Features sequin details and flattering silhouette.',
    3999.00,
    3499.00,
    ARRAY['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500'],
    'Dresses',
    ARRAY['XS', 'S', 'M', 'L'],
    ARRAY['Gold', 'Silver', 'Rose Gold', 'Black'],
    true,
    15,
    true,
    ARRAY['party', 'cocktail', 'sequin', 'glamour'],
    4.9,
    78
),
(
    'Denim Jacket',
    'Classic denim jacket that completes any outfit. Durable and stylish with a comfortable fit.',
    2499.00,
    1999.00,
    ARRAY['https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=500'],
    'Tops',
    ARRAY['S', 'M', 'L', 'XL'],
    ARRAY['Light Blue', 'Dark Blue', 'Black'],
    true,
    35,
    false,
    ARRAY['denim', 'jacket', 'casual'],
    4.5,
    92
),
(
    'Bohemian Maxi Skirt',
    'Flowing bohemian style maxi skirt with beautiful patterns. Perfect for a relaxed, stylish look.',
    1799.00,
    1499.00,
    ARRAY['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500'],
    'Bottoms',
    ARRAY['S', 'M', 'L', 'XL'],
    ARRAY['Multi-color', 'Beige', 'Navy'],
    true,
    28,
    false,
    ARRAY['bohemian', 'maxi', 'skirt', 'casual'],
    4.3,
    54
),
(
    'Silk Evening Gown',
    'Luxurious silk evening gown for your most special occasions. Elegant draping and sophisticated design.',
    8999.00,
    7499.00,
    ARRAY['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500'],
    'Dresses',
    ARRAY['XS', 'S', 'M', 'L'],
    ARRAY['Champagne', 'Emerald', 'Burgundy', 'Black'],
    true,
    10,
    true,
    ARRAY['silk', 'gown', 'luxury', 'formal'],
    5.0,
    34
),
(
    'Casual Crop Top',
    'Trendy crop top perfect for casual outings. Comfortable cotton blend fabric.',
    799.00,
    599.00,
    ARRAY['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500'],
    'Tops',
    ARRAY['XS', 'S', 'M', 'L'],
    ARRAY['White', 'Black', 'Pink', 'Mint Green'],
    true,
    60,
    false,
    ARRAY['crop', 'casual', 'trendy'],
    4.2,
    203
);

-- Verify products were added
SELECT COUNT(*) as total_products FROM products;
